# Site settings
title: crabacus
email: "crabacus 6 [at] gmail.com"
description: "This is my website where I post music that I make. ^^"
baseurl: ""
url: "http://yourdomain.com"
github_username:  crabacus

# Build settings
markdown: kramdown
permalink: pretty

sass:
    sass_dir: _sass